In [1]:
# Import the necessary libraries
# You will likely need to install a number of these modules/libraries
# (e.g. pip install geopandas or conda install geopandas)
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px

In [2]:
# This is unnecessary if you plan to run the notebook from JupyterLab (locally, or from the OTU hub at https://hub.science.ontariotechu.ca/)
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# Read in the data (make sure you download each file and place them in a "data" directory where your .ipynb is located)
cities = pd.read_csv('/content/drive/Shareddrives/MBAI 5400G - Visualization and Storytelling (Winter 2026)/In-Class Activities/Python Visualization/data/minard-cities.csv')
troops = pd.read_csv('/content/drive/Shareddrives/MBAI 5400G - Visualization and Storytelling (Winter 2026)/In-Class Activities/Python Visualization/data/minard-troops.csv')
weather = pd.read_csv('/content/drive/Shareddrives/MBAI 5400G - Visualization and Storytelling (Winter 2026)/In-Class Activities/Python Visualization/data/minard-temp.csv')
cities.head()

   long   lat  survivors direction  group      city
0  24.0  54.9     340000   Advance      1     Kowno
1  24.5  55.0     340000   Advance      1       NaN
2  25.5  54.5     340000   Advance      1       NaN
3  26.0  54.7     320000   Advance      1  Smorgoni
4  27.0  54.8     300000   Advance      1       NaN

In [4]:
named_city = cities[cities['city'].notna()]
named_city

    long   lat  survivors direction  group         city
0   24.0  54.9     340000   Advance      1        Kowno
3   26.0  54.7     320000   Advance      1     Smorgoni
5   28.0  54.9     280000   Advance      1    Gloubokoe
6   28.5  55.0     240000   Advance      1      Polotzk
9   30.3  55.3     175000   Advance      1      Witebsk
12  34.4  55.5     127100   Advance      1        Chjat
15  37.6  55.8     100000   Advance      1       Moscou
25  37.7  55.7     100000   Retreat      1       Moscou
28  36.8  55.0      96000   Retreat      1      Mojaisk
31  33.3  54.8      37000   Retreat      1  Dorogobouge
36  32.0  54.6      24000   Retreat      1     Smolensk
38  29.2  54.3      20000   Retreat      1         Bobr
39  28.5  54.2      20000   Retreat      1   Studienska
41  27.5  54.5      20000   Retreat      1        Minsk
43  26.8  54.3      12000   Retreat      1    Moiodexno
48  24.4  54.4       4000   Retreat      1        Wilna

In [5]:
fig = px.scatter_geo(named_city,lat='lat',lon='long',color='direction',
                     hover_name='city',size='survivors',projection='equirectangular',scope='europe',
                     title='Minard map')
fig.show()

In [6]:
survivors = px.density_mapbox(troops, lat = 'lat', lon = 'long',
                         z = 'survivors',
                         center = dict(lat = 55, lon = 30),
                         zoom = 4.7,
                         hover_name = 'direction',
                         mapbox_style = 'carto-positron'
                         )
survivors.show()